feat: add full screen loader to field
lewxdev/mmmines pull request #24
Opened 2024-08-10 19:07 UTC by drewradcliff

2024-08-10 19:17 UTC, lewxdev requested changes

2024-08-10 19:17 UTC, lewxdev commented on app/components/field.tsx
> +    <div className="absolute bg-white h-full w-full left-0 right-0">
may not need `left-0` and `right-0` if you have `h-full` and `w-full` (which can be `w-[100dvw]` `h-[100dvh]`.
also, do we need z-index here?

2024-08-10 19:17 UTC, lewxdev commented on app/components/field.tsx
> +          className="animate-pulse"
```suggestion
          className="grid animate-pulse"
          style={{
            gap: `${GAP_SIZE}rem`,
            gridTemplateColumns: `repeat(3, ${GRID_SIZE}rem)`,
          }}
```

2024-08-10 19:17 UTC, lewxdev commented on app/components/field.tsx
> +          ))}
```suggestion
          {Array.from({ length: 9 }, (_, index) => (
            <div
              key={index}
              className="bg-gray-100"
              style={{ height: `${GRID_SIZE}rem`, width: `${GRID_SIZE}rem` }}
            />
          ))}
```

2024-08-10 19:17 UTC, lewxdev commented on app/components/header.tsx
haha, whoopsie

2024-08-10 22:07 UTC, drewradcliff commented on app/components/header.tsx
> +                <span className="">{exposedPercent}</span>
```suggestion
                <span>{exposedPercent}</span>
```

2024-08-12 20:37 UTC, lewxdev requested changes
last one and it should be good 👍🏽

2024-08-12 20:37 UTC, lewxdev commented on app/components/header.tsx
> +            )}
```suggestion 
          {!!clientsCount && (
            <div className="flex items-center gap-2">
              <span>{clientsCount}</span>
              <UsersIcon className="h-4 w-4" />
            </div>
          )}
```

2024-08-12 20:37 UTC, lewxdev commented on app/components/header.tsx
> +          </div>
```suggestion
          {!!exposedPercent && (
            <div className="flex items-center justify-end gap-2">
              <span>{exposedPercent}</span>
              <Percent className="h-4 w-4" />
            </div>
          )}
```

2024-08-12 21:07 UTC, lewxdev approved these changes
🤞🏽

2024-08-12 21:10 UTC, merged