auth
lewxdev/mmmines pull request #28
Opened 2024-08-17 17:30 UTC by drewradcliff

- **feat: add socket session data**
- **fix: types and make concise**

2024-08-19 00:47 UTC, drewradcliff commented on package.json
> +    "zoo-ids": "2.0.6"
uninstall zoo-ids

2024-08-20 22:18 UTC, lewxdev requested changes
welp
![image](https://github.com/user-attachments/assets/084cfafc-31af-4f9c-9b30-d8a40c0d1c0b)

2024-08-20 22:18 UTC, lewxdev commented on app/types/index.ts
> +  session: ({ sessionID }: { sessionID: string }) => void;
since we're only concerned with the session, we can drop the use of an object here (also, I'm personally partial to using `sessionId` over `sessionID`)
```suggestion
  session: (sessionId: string) => void;
```

2024-08-20 22:18 UTC, lewxdev commented on app/types/index.ts
> +};
```suggestion
type SocketData = {
  sessionId: string;
};
```

2024-08-20 22:18 UTC, lewxdev commented on app/types/index.ts
> +>;
...that's my bad, this should be `InterServerEvents`
...keeping the order as is used in the generic would please my ocd ❤️
...now that I think about it, it should also be `ClientSocket` and `ServerSocket` too 🙃
```suggestion
type InterServerEvents = {};

type SocketData = {
  sessionID: string;
};

export type ClientSocket = Socket<ServerToClientEvents, ClientToServerEvents>;

export type ServerSocket = Server<
  ClientToServerEvents,
  ServerToClientEvents,
  InterServerEvents,
  SocketData
>;
```

or if you want to be more correct, and keep everything but the name
```suggestion
type InterServerEvents = {
  [event: string]: (...args: any[]) => void;
};

type SocketData = {
  sessionID: string;
};

export type ClientSocket = Socket<ServerToClientEvents, ClientToServerEvents>;

export type ServerSocket = Server<
  ClientToServerEvents,
  ServerToClientEvents,
  InterServerEvents,
  SocketData
>;
```

see: [Socket.IO | TypeScript | Types for the server](https://socket.io/docs/v4/typescript/#types-for-the-server)

2024-08-20 22:18 UTC, lewxdev commented on app/server.ts
> +import type { SocketServer } from "@/types";
```suggestion
import type { ServerSocket } from "@/types";
```

2024-08-20 22:18 UTC, lewxdev commented on app/server.ts
> +  const io: SocketServer = new Server(httpServer);
```suggestion
  const io: ServerSocket = new Server(httpServer);
```

2024-08-20 22:18 UTC, lewxdev commented on app/server.ts
> +    next();
this can be simplified a bit. maybe this is a little clearer also
```suggestion
    const { sessionId } = socket.handshake.auth;
    const sessionState = sessions.get(sessionId);
    if (sessionState === "dead") {
      return next(new Error("dead"));
    }
    socket.data.sessionId = sessionState === "alive"
      ? sessionId
      : crypto.randomBytes(8).toString("hex");
    next();
```

2024-08-20 22:18 UTC, lewxdev commented on app/server.ts
> +    });
```suggestion
    sessions.set(socket.data.sessionId, "alive");
    socket.emit("session", socket.data.sessionId);
```

2024-08-20 22:18 UTC, lewxdev commented on app/server.ts
>        io.emit("update", field.plots);
we can omit naming this variable (I heard you don't like naming things) also, we may not have to do anything other than emit `"update"` afterwards
```suggestion
      if (field.exposeCell(index) === "dead") {
        sessions.set(socket.data.sessionId, "dead");
        socket.emit("death");
      } else {
        field = await field.handleComplete();
        io.emit("exposedPercent", field.exposedPercent);
      }
      io.emit("update", field.plots);
```

2024-08-20 22:18 UTC, lewxdev commented on app/layout.tsx
> +import { SocketProvider } from "@/components/socket-provider";
curious that prettier didn't catch this
```suggestion
import { Header } from "@/components/header";
import { SocketProvider } from "@/components/socket-provider";
import "@/globals.css";
```

2024-08-20 22:18 UTC, lewxdev commented on app/components/socket-provider.tsx
> +const socket: SocketClient = io({ autoConnect: false });
I saw in the docs you can use a callback for auth, maybe we can look into it, maybe we don't have to worry about emitting `"session"`. more research is needed though
[Socket.IO | Middlewares | Sending credentials](https://socket.io/docs/v4/middlewares/#sending-credentials)

```ts
const socket: SocketClient = io({
  auth: () => localStorage.getItem('sessionId'),
  // autoConnect: false, // may or may not need this
});
```

2024-08-20 22:18 UTC, lewxdev commented on app/components/socket-provider.tsx
> +}
we should make this `null` by default and use the convention outlined in the React TypeScript Cheatsheet, that way we can ensure the socket is connected before accessing events with `useSocketEvent`
```suggestion
type SocketContextValue = {
  socket: SocketClient;
  isDead: boolean;
}

const SocketContext = createContext<SocketContextValue | null>(null);

export function useSocket() {
  const value = useContext(SocketContext);
  if (!value) {
    throw new Error("useSocket should be used in SocketProvider");
  }
  return value;
}
```

see: [React TypeScript Cheatsheet | Context | Without default context value](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/context#without-default-context-value)

2024-08-20 22:18 UTC, lewxdev commented on app/components/socket-provider.tsx
> +  );
we can get rid of the extra `console.log`s for now, maybe we can look into socket server logging in development either with debug or middleware
see: [Socket.IO | Logging and debugging](https://socket.io/docs/v4/logging-and-debugging/)

also, I'm not the biggest fan of `isDead`, we can just use the same value that we store in redis
also also, I'm wondering if we should persist the loading state if we're still trying to retrieve the session state (so we don't get layout shift or flashbanged)
also also also, I'm tempted to rename the `"session"` and `"death"` events to be clearer, maybe `"session_alive"` and `"session_dead"`
I've also reordered the event listeners here for my own sanity

```ts
  const [sessionState, setSessionState] = useState<"alive" | "dead" | null>(null);

  useEffect(() => {
    socket.auth = { sessionId: localStorage.getItem("sessionId") };
    socket.connect();

    socket.on("connect_error", (error) => {
      if (error.message === "dead") {
        setSessionState("dead");
      }
    });

    socket.on("session_alive", (sessionId) => {
      setSessionState("alive");
      socket.auth = { sessionId };
      localStorage.setItem("sessionId", sessionId);
    });
    
    socket.on("session_dead", () => {
      setSessionState("dead");
    });
  }, []);

  return (
    <SocketContext.Provider value={{ socket, sessionState }}>
      {children}
    </SocketContext.Provider>
  );
```

2024-08-20 22:18 UTC, lewxdev commented on app/hooks/use-socket-event.ts
> +  const { socket } = useSocket();
fail fast (provided you initialize context to `null`)

```suggestion
  const { socket } = useSocket();
  const [result, setResult] = useState<
    Parameters<ServerToClientEvents[K]> | []
  >([]);
```

2024-08-20 22:18 UTC, lewxdev commented on app/components/plot.tsx
> +
```suggestion
  const { socket } = useSocket();
```

2024-08-20 22:18 UTC, lewxdev commented on app/components/field.tsx
> +  const { isDead } = useSocket();
```suggestion
  const { isDead } = useSocket();
  const [plots] = useSocketEvent("update");
```

2024-08-20 22:50 UTC, drewradcliff commented on app/components/socket-provider.tsx
> +const socket: SocketClient = io({ autoConnect: false });
Created a ticket

2024-08-21 01:01 UTC, lewxdev approved these changes
lgtm
![image](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2g4cm5wbzNjZXpkbHo5emkzNHR4amh4MTczZzdpMGRyNGlubGFteSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/WFyvwq3xoTTMs/giphy.gif)

2024-08-21 01:02 UTC, merged